name: Deploy storybook

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1.4.3
      - name: Yarn install
        run: npm install
      - name: Deploy
        run: npm run deploy-storybook -- --ci
