name: Deploy storybook

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1.4.3
      - name: Checkout repo
        uses: actions/checkout@v2.3.2
      - name: Setup git
        run: git remote rm origin && git remote add origin 'git@github.com:Lotes/touchi-touchi-fummel-fummel.git'
      - name: Yarn install
        run: yarn install
      - name: Deploy
        run: yarn run deploy-storybook -- --ci
