name: Deploy storybook

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1.4.3
      - name: Checkout repo
        run: git clone git@github.com:Lotes/touchi-touchi-fummel-fummel.git
      - name: Yarn install
        run: yarn install
      - name: Deploy
        run: yarn run deploy-storybook -- --ci
